<template>


  <h1 v-if="twoFactorComplete">
    Welcome Successfully SignIn!!!
  </h1>

  <div class="flex justify-center items-center">
    <template v-if="isTwoFactorAuthenticationSetup">
      <UCard class="lg:w-1/3 md:w-1/2 xl:w-1/3 sm:w-full">
        <h1 class="text-center text-lg font-bold">Set up Two-Factor Authentication</h1>

        <!-- Step 1: Show QR Code -->
        <template v-if="isTwoFactorAuthenticationSetup">
          <p class="text-center">Scan the QR code below with your authenticator app.</p>
          <div class="flex justify-center">
            <img :src="qrcode" alt="QR Code for 2FA"/>
          </div>
          <p class="text-center mt-4">After scanning, enter the 6-digit code generated by the app below.</p>

          <!-- Step 2: Enter the 6-digit code -->
          <UForm :schema="schema" :state="state" @submit="onSubmitCode" class="space-y-4">
            <UFormGroup label="2FA Code" name="code">
              <UInput v-model="state.code" placeholder="Enter the 6-digit code" maxlength="6"/>
            </UFormGroup>

            <UButton type="submit">
              Verify 2FA Code
            </UButton>
          </UForm>
        </template>
        <!--        <template v-if="twoFactorComplete">-->
        <!--          <p class="text-center text-green-600">Two-Factor Authentication setup is complete! You can now sign in with 2FA enabled.</p>-->
        <!--        </template>-->
      </UCard>
    </template>
    <template v-else-if="isTwoFactorAuthentication">
      <UCard class="lg:w-1/3 md:w-1/2 xl:w-1/3 sm:w-full">
        <p class="text-center mt-4">Enter the 6-digit code generated by the authenticator app below.</p>
        <UForm :schema="schema" :state="state" @submit="onSubmitCode" class="space-y-4">
          <UFormGroup label="2FA Code" name="code">
            <UInput v-model="state.code" placeholder="Enter the 6-digit code" maxlength="6"/>
          </UFormGroup>

          <UButton type="submit">
            Verify 2FA Code
          </UButton>
        </UForm>
      </UCard>
    </template>
    <template v-else-if="!twoFactorComplete && !isTwoFactorAuthenticationSetup && !isTwoFactorAuthentication">
      <UCard class="lg:w-1/3 md:w-1/2 xl:w-1/3 sm:w-full">
        <UForm :schema="schema" :state="state" @submit="onSubmit" class="space-y-4">
          <UFormGroup label="Email" name="email">
            <UInput v-model="state.email"/>
          </UFormGroup>

          <UFormGroup label="Password" name="password">
            <UInput v-model="state.password" type="password"/>
          </UFormGroup>

          <UButton type="submit">
            Prisijungti
          </UButton>
        </UForm>
      </UCard>
    </template>
  </div>


</template>

<script lang="ts" setup>

import {z} from 'zod'


import type {FormSubmitEvent} from "#ui/types";
import {useQRCode} from '@vueuse/integrations/useQRCode'

const isTwoFactorAuthenticationSetup = ref(false);
const isTwoFactorAuthentication = ref(false);
const twoFactorComplete = ref(false);
const text = ref('');
const userId = ref('');
const qrcode = useQRCode(text);

const PROD_BASE_URL = 'https://vikosoftware-production.up.railway.app';
const TEST_BASE_URL = 'http://localhost:5296';


const schema = z.object({
  email: z.string().email('Invalid email'),
  password: z.string().min(8, 'Must be at least 8 characters')
})

type Schema = z.output<typeof schema>

const state = reactive({
  email: undefined,
  password: undefined,
  code: undefined
})

async function onSubmit(event: FormSubmitEvent<Schema>) {
  // Do something with data
  console.log(event.data);
  await loginAdministration(event.data.email, event.data.password);

}

async function onSubmitCode(event) {
  console.log('2FA Code:', event.data.code);

  // Call your backend to verify the 2FA code
  await verifyTwoFactorCode(event.data.code);
}


// const msAuth = useMSAuth();
//
// async function login() {
//   await msAuth.signIn()
// }


async function loginAdministration(username: string, password: string) {
  const url = `${PROD_BASE_URL}/auth/mfa/signin`;
  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Accept': 'text/plain',
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        email: username,
        password: password
      }),
    });

    if (!response.ok) {
      // Handle error response
      const errorData = await response.text();
      console.error('Error:', errorData);
      throw new Error('Failed to login');
    }
    const responseData = await response.json();
    console.log('Success:', responseData);

    if (responseData.message === '2FA setup required') {
      isTwoFactorAuthenticationSetup.value = true;
      text.value = responseData.qrCodeUrl;
      userId.value = responseData.userId;
    } else if (responseData.message === '2FA required') {
      isTwoFactorAuthentication.value = true;
      isTwoFactorAuthenticationSetup.value = false;
      userId.value = responseData.userId;
    }

    return responseData;
  } catch (error) {
    console.error('Error:', error);
    throw error;
  }
}


// Backend API to verify the 2FA code
async function verifyTwoFactorCode(code: string) {
  const url = `${PROD_BASE_URL}/auth/mfa/verify-2fa`;

  try {
    const response = await fetch(url, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Accept': 'application/json'
      },
      body: JSON.stringify({
        userId: userId.value,
        verificationCode: code
      }),
      credentials: 'include' // Add this option to include cookies
    });

    if (response.ok) {
      console.log('2FA verification success');
      twoFactorComplete.value = true;
      isTwoFactorAuthenticationSetup.value = false;
      isTwoFactorAuthentication.value = false;
    } else {
      const errorData = await response.text();
      console.error('2FA verification failed:', errorData);
    }
  } catch (error) {
    console.error('Error verifying 2FA code:', error);
  }
}


</script>

<style scoped>

</style>
